<a href="https://colab.research.google.com/github/ynpreet/Fake-data-generation/blob/main/OTT_data_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive._mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install Faker
from faker import Faker

Collecting Faker
  Downloading Faker-11.3.0-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 5.0 MB/s
Requirement already satisfied: typing-extensions>=3.10.0.2 in /usr/local/lib/python3.7/dist-packages (from Faker) (3.10.0.2)
Requirement already satisfied: text-unidecode==1.3 in /usr/local/lib/python3.7/dist-packages (from Faker) (1.3)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.7/dist-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.4->Faker) (1.15.0)
Installing collected packages: Faker
Successfully installed Faker-11.3.0

In [ ]:

# import pandas as pd
# import random
# from faker import Faker
# from random import randrange
# from datetime import datetime

# nr_of_customers = 1000

# fake = Faker('de_DE')

# customers = []

# for customers_id in range(nr_of_customers):

#     # Create transaction date 
#     d1 = datetime.strptime(f'1/1/2021', '%m/%d/%Y')
#     d2 = datetime.strptime(f'8/10/2021', '%m/%d/%Y')
#     transaction_date = fake.date_between(d1, d2)

#     #create customer's name
#     name = fake.name()

#     # Create gender
#     gender = random.choice(["M", "F"])

#     # Create email 
#     email = fake.ascii_email()

#     #Create city
#     city = fake.city()

#     #create product ID in 8-digit barcode
#     product_ID = fake.ean(length=8)
    
#     #create amount spent
#     amount_spent = fake.pyfloat(right_digits=2, positive=True, min_value=1, max_value=100)

#     customers.append([transaction_date, name, gender, email, city, product_ID, amount_spent])

# customers_df = pd.DataFrame(customers, columns=['Transaction_date','Name', 'Gender','Email', 'City','Product_id', 'Amount_spent']) 
                
# pd.pandas.set_option('display.max_columns', None)
# print(customers_df)

In [ ]:

import pandas as pd
import random
from faker import Faker
from random import randrange
from datetime import datetime

nr_of_customers = 40000

fake = Faker('de_DE')

customers = []

for customers_id in range(nr_of_customers):

    # Create User_ID
    user_ID = fake.ean(length=8)
    #create user's's name
    name = fake.name()
    # Create gender
    gender = random.choice(["M", "F"])
    
    # Create date of birth 
    d1 = datetime.strptime(f'1/1/1947', '%m/%d/%Y')
    d2 = datetime.strptime(f'8/10/2003', '%m/%d/%Y')
    date_of_birth = fake.date_between(d1, d2)

    # Create email 
    email = fake.ascii_email()

    #Create city
    city = fake.city()

    #Create state
    state = fake.state()
    #Create country
    country = fake.country()

    # Create Signupdate 
    d1 = datetime.strptime(f'1/1/2007', '%m/%d/%Y')
    d2 = datetime.strptime(f'8/10/2022', '%m/%d/%Y')
    signup_date = fake.date_between(d1, d2) 
    
    # Create Transactiondate
    d1 = datetime.strptime(f'1/1/2007', '%m/%d/%Y')
    d2 = datetime.strptime(f'8/10/2022', '%m/%d/%Y')
    Transaction_date = fake.date_between(d1, d2)

    # Create cancel date 
    d1 = datetime.strptime(f'1/1/2008', '%m/%d/%Y')
    d2 = datetime.strptime(f'8/10/2022', '%m/%d/%Y')
    cancel_date = fake.date_between(d1, d2)

    # Create status
    status = random.choice(["Active", "Inactive"])

    #create amount spent
    amount_spent = fake.pyfloat(right_digits=2, positive=True, min_value=1, max_value=100)

    #create amount gained
    amount_gained = fake.pyfloat(right_digits=2, positive=True, min_value=1, max_value=1000)


#     my_word_list = [
#     'danish','cheesecake','sugar',
#     'Lollipop','wafer','Gummies',
#     'sesame','Jelly','beans',
#     'pie','bar','Ice','oat' ]

# fake.sentence()
# # 'Expedita at beatae voluptatibus nulla omnis.'

# fake.sentence(ext_word_list=my_word_list) 

    customers.append([user_ID , name, gender, date_of_birth, email, city,state,country,signup_date, Transaction_date,cancel_date, status, amount_spent,amount_gained])

customers_df = pd.DataFrame(customers, columns=['user_ID' , 'name', 'gender', 'date_of_birth', 'email', 'city','state','country','signup_date', 'Transaction_date','cancel_date', 'status', 'amount_spent','amount_gained']) 
                
pd.pandas.set_option('display.max_columns', None)
# print(customers_df)

In [ ]:
import numpy as np
customers_df['cancel_date'] = np.where((customers_df.status == 'Active'),'',customers_df.cancel_date)
customers_df

,user_ID,name,gender,date_of_birth,email,city,state,country,signup_date,Transaction_date,cancel_date,status,amount_spent,amount_gained
0,01189605,Dan Geißler-Mende,M,1964-08-11,jockelnuri@hein.com,Mettmann,Brandenburg,Guatemala,2013-11-30,2014-06-19,2008-11-09,Inactive,13.54,747.31
1,28219910,Marlies Gerlach,M,1994-03-26,ruppersbergerclaudia@eberth.de,Schwäbisch Gmünd,Bayern,St. Martin,2009-09-05,2016-08-07,2014-01-07,Inactive,41.50,380.80
2,86780278,Katherina Textor B.Eng.,F,1986-05-30,othmarkoch@yahoo.de,Hansestadttralsund,Baden-Württemberg,Mayotte,2010-10-14,2014-07-05,2021-04-18,Inactive,50.10,519.80
3,76067907,Dana Lindau,M,1969-06-24,johannemueller@yahoo.de,Freudenstadt,Rheinland-Pfalz,Spanien,2010-08-19,2014-01-08,,Active,5.58,761.76
4,00783088,Mehmet Schuster-Binner,F,1960-04-24,gisbert69@bien.org,Brand,Sachsen,Bangladesch,2014-04-11,2013-01-24,,Active,39.85,764.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,28000792,Karl Heinz Kuhl B.A.,M,1963-03-17,warmergino@googlemail.com,Sonneberg,Bremen,Österreich,2013-09-25,2012-01-29,,Active,80.20,7.68
39996,23424609,Luisa Müller,M,1958-08-02,staudejorge@heydrich.com,Oschatz,Nordrhein-Westfalen,Taiwan,2007-10-21,2013-07-10,,Active,67.28,970.29
39997,08302250,Norman Schuster,F,1951-12-30,vwirth@web.de,Stadtroda,Sachsen-Anhalt,Bahamas,2007-03-31,2010-01-07,,Active,56.84,345.49
39998,05794706,Andreas Hande,F,1996-06-01,friedavan-der-dussen@stroh.de,Berlin,Hessen,Paraguay,2011-04-28,2019-08-11,,Active,49.74,68.79
39999,72277997,Ulf Sauer,F,1998-08-09,ortmannhildegart@pergande.de,Calw,Nordrhein-Westfalen,Indonesien,2007-03-01,2017-12-06,,Active,93.50,958.38

In [ ]:
netflix=pd.read_csv('/content/netflix_titles.csv')

In [ ]:
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:

import pandas as pd
import random
from faker import Faker
from random import randrange
from datetime import datetime

nr_of_OTT = 10000000

fake = Faker('de_DE')

OTT = []

for i in range(nr_of_OTT):

    # Create User_ID
    user_ID = random.choice(customers_df.user_ID)
    # date 
    d1 = datetime.strptime(f'1/1/1947', '%m/%d/%Y')
    d2 = datetime.strptime(f'8/10/2003', '%m/%d/%Y')
    date = fake.date_between(d1, d2)

    # Create engagement 
    engagement = random.choice(['Yes','No'])

    #Program watched
    Program = random.choice(netflix.title)

    #STart time
    start_time=fake.time()

    #end time
    end_time=fake.time()

    #Create Device viewership
    Device_viewership = random.choice(['mobile', 'ROKU',' Apple TV'])

    OTT.append([user_ID ,date, engagement,Program,start_time,end_time,Device_viewership])

OTT = pd.DataFrame(OTT, columns=['user_ID' ,'date', 'engagement','Program','start_time','end_time','Device_viewership']) 
                
pd.pandas.set_option('display.max_columns', None)
# print(customers_df)

In [ ]:
OTT.to_csv('/content/drive/MyDrive/Colab files/OTT/OTT.csv')

In [ ]:
# OTT['Duration']=abs(OTT['end_time']-OTT['start_time'])
OTT.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000000 entries, 0 to 9999999
Data columns (total 8 columns):
 #   Column             Dtype
---  ------             -----
 0   user_ID            object
 1   date               object
 2   engagement         object
 3   Program            object
 4   start_time         datetime64[ns]
 5   end_time           datetime64[ns]
 6   Device_viewership  object
 7   Duration           timedelta64[ns]
dtypes: datetime64[ns](2), object(5), timedelta64[ns](1)
memory usage: 610.4+ MB

In [ ]:
# df['Dates'] = pd.to_datetime(df['Dates'], format='%y%m%d')
# OTT['start_time']=pd.to_datetime(OTT['start_time'], format='%H:%M:%S')
# OTT['end_time']=pd.to_datetime(OTT['end_time'], format='%H:%M:%S')

In [ ]:
# OTT.head()
# OTT['Duration']=OTT['Duration'].time()
# for d in OTT['Duration']:
#    OTT['time'] = dt.time
# OTT['time']=pd.to_datetime(OTT['Duration']).dt.time
# OTT['Duration']=OTT['Duration'].values.astype('datetime64[D]')
OTT['new_time'] = [d.time() for d in OTT['Duration']]

AttributeError: ignored

In [ ]:
OTT.head()

,user_ID,date,engagement,Program,start_time,end_time,Device_viewership,Duration
0,02102238,1965-08-11,Yes,Thunder Force,1900-01-01 22:03:40,1900-01-01 07:02:24,Apple TV,0 days 15:01:16
1,55977876,1988-09-23,No,Like Father,1900-01-01 05:59:50,1900-01-01 01:03:54,mobile,0 days 04:55:56
2,35388005,1976-06-24,Yes,Maron,1900-01-01 16:32:04,1900-01-01 10:06:21,Apple TV,0 days 06:25:43
3,84288936,2001-09-11,Yes,GIMS: On the Record,1900-01-01 15:11:59,1900-01-01 15:10:58,ROKU,0 days 00:01:01
4,95010007,1953-09-12,No,9,1900-01-01 03:52:44,1900-01-01 05:35:33,Apple TV,0 days 01:42:49